### ISSUE TITLE
64-bit python support

### ISSUE THREAD

**Issue by andyclegg** [armstrap/armstrap-pyvirtualbench#11]
My version of the NI driver (18.0.0) comes with a lib64 compiled nivirtualbench.lib. Would it be possible to update the Python wrapper to support this?

I can run `ps_example.py` fine on 32-bit Python, but on 64-bit I get:
```$ python examples/ps_example.py
Traceback (most recent call last):
  File "examples/ps_example.py", line 43, in <module>
    ps = virtualbench.acquire_power_supply()
  File "C:\Users\User\armstrap-pyvirtualbench\lib\pyvirtualbench.py", line 1938, in acquire_power_supply
    return self.PowerSupply(self, device_name, reset)
  File "C:\Users\User\armstrap-pyvirtualbench\lib\pyvirtualbench.py", line 1946, in __init__
    status = self.nilcicapi.niVB_PS_InitializeW(self.library_handle, c_wchar_p(self.device_name), c_bool(reset), byref(self.instrument_handle))
OSError: exception: access violation reading 0x0000000063AB4490

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/ps_example.py", line 56, in <module>
    virtualbench.release()
  File "C:\Users\User\armstrap-pyvirtualbench\lib\pyvirtualbench.py", line 382, in release
    status = self.nilcicapi.niVB_Finalize(self.library_handle)
OSError: exception: access violation writing 0x0000000063AB4498
```

If you can provide any guidance on what changes would be necessary, I can look into doing this and submitting a PR.

**Comment by moritzj29** [comment]
Hi @andyclegg ,
I stumbled upon the same issue today. I managed to get it working in 64bit Python, please see the PR #12 . It would be great if you could check if it works for you as well. Maybe you have some additional ideas to make these changes more elegant...

**Comment by thosou** [comment]
Hi @moritzj29,
I met the same problem and I can confirm your fix in PR #12 works. 
Thanks!

**Comment by souviksaha97** [comment]
Can confirm it works @moritzj29

**Comment by armstrap** [comment]
Accepted PR[#12](https://github.com/armstrap/armstrap-pyvirtualbench/pull/12).  Closing, thanks.
