### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by brownac3** [armstrap/armstrap-pyvirtualbench#4]
Hello,

Could someone help me with the install of pyVirtualBench? I put the pyvirutalbench.py file in my "C:\Anaconda2\lib" folder by when I run one of the example programs i get the following error: "WindowsError: [Error 126] The specified module could not be found"

**Comment by armstrap** [comment]
Try the following
```
mkdir Projects
cd Projects
git clone https://github.com/armstrap/armstrap-pyvirtualbench.git
cd armstrap-pyvirtualbench
set PYTHONPATH=lib
python examples\p2_example.py
```
That should get you going.
