### ISSUE TITLE
Issue with I2C example

### ISSUE THREAD

**Issue by PPCanuck** [armstrap/armstrap-pyvirtualbench#5]
Hi there,

First of all, big kudos for pushing this project out.  I love my VBench and used your examples successfully for the frequency generator without problems.  However, I'm having an issue with the I2C example.  First I was getting an issue from the acquire_inter_integrated_circuit command.  Comparing the class structure to the SPI class, it looked like line 2201 should have been

self.bus = bus

rather than
self.bus = outer.bus

This stopped an issue with running the code (SPI_Example runs fine by the way).  However, then I get an issue with C types as shown below:
<<
![image](https://user-images.githubusercontent.com/43079724/45245291-fe998280-b2b8-11e8-9486-5434fe390d4d.png)

>>

but basically a NameError on the c_uint16 of the address variable.

Any ideas you have would be MOST appreciated!  I am looking at the updated NI Driver (rev 1.2 -> I'm using 1.1.1) so maybe that already resolves this bug?

Side note - how do you decide which of the digital IO lines are the SCLK/SDA?  I couldn't really tell that in the example code.

Thanks!
-Paul

**Comment by aclark1983** [comment]
Paul,

Did you have any luck resolving this issue yourself?

AC

**Comment by PPCanuck** [comment]
Hi there,
I gave up and used my Aardvark instead.
Thanks,
-Paul

Paul Perrault, M. Sc., P. Eng
Senior Staff Field Applications Engineer

Mobile    (403) 614-4721
Web        analog.com<http://www.analog.com/>
Cochrane, AB, Canada

Linear Technology is now part of Analog Devices.  Learn more<http://www.analog.com/en/landing-pages/001/adi-linear-combine/index.html>.
[cid:image002.png@01D45B0B.98B8E910]

**Comment by armstrap** [comment]
This was recently fixed.  Can you give it another try?

**Comment by armstrap** [comment]
Closing issue as already resolved.  If you are still having problems, let me know.
