### ISSUE TITLE
Local device name passings to API call

### ISSUE THREAD

**Issue by tcemmene** [armstrap/armstrap-pyvirtualbench#6]
Hi there

Just two small issues: 

1. In method `set_calibration_information(..)` on `line 493` there is a wrong passing of the local device name to the API call, because the class member `c_wchar_p(device_name)` is passed directly, instead of `c_wchar_p(local_device_name)`.

2. In method `set_calibration_password(..)` on `line 502` the assignment of `local_device_name = ..` is missing completely and is therefore not being passed to the API call.

Thank you for your work.

**Comment by tcemmene** [comment]
Hello

Here's one more issue:

- On `line 822` - in the constructor of `FunctionGeneratorCalibration` - the reference to the `self.instrument_handle` should be passed, not the handler value: `byref(self.instrument_handle)`

Thank you.

**Comment by armstrap** [comment]
Thanks for catching this!  This is fixed in https://github.com/armstrap/armstrap-pyvirtualbench/commit/fc1f978622800fa9cbcf5dc7bb62015086bb3f9d
