### ISSUE TITLE
NameError: name 'virtualbench' is not defined

### ISSUE THREAD

**Issue by liamtrz** [armstrap/armstrap-pyvirtualbench#7]
Hi all

I have attempted to run a few of the example scripts however I keep running into the same error " NameError: name 'virtualbench' is not defined ". I believe that I have followed the correct steps outlined in the commenting and documentation so any input would be very much appreciated.

**Comment by armstrap** [comment]
Which example?  Each example requires you to change the name 'myVirtualBench' string to the name of your VirtualBench device.
```
    # You will probably need to replace "myVirtualBench" with the name of your device.
    # By default, the device name is the model number and serial number separated by a hyphen; e.g., "VB8012-309738A".
    # You can see the device's name in the VirtualBench Application under File->About
    virtualbench = PyVirtualBench('myVirtualBench')
```
